version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5555:5432'
    restart: always
    env_file:
      - .env.local
    volumes:
      - postgres_data:/data/postgres

volumes:
  postgres_data:
