name: Database Migration

on:
  push:
    branches:
      - main

jobs:
  migrate:
    name: Run Database Migrations
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '9.9.0'
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build workspace packages
        run: pnpm build-packages
        
      - name: Run database migrations
        run: pnpm db:deploy
        env:
          # Add your database connection string and other required environment variables
          DATABASE_URL: ${{ secrets.SMB_FINANCIAL_MANAGEMENT_DATABASE_URL }}
          # Add any other environment variables needed for database connection